package com.ulimbridge.wordmafia;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.SQLException;
import android.database.sqlite.SQLiteDatabase;
import android.util.Log;

import java.util.regex.Pattern;

import static android.content.ContentValues.TAG;

public class WordDBRecord999 {

    public String id;
    public String category;
    public String word;
    private Context context;
    private WordDBHelper999 dbHelper;
    private SQLiteDatabase database;
    Singleton_Setting99 s1 = Singleton_Setting99.getInstance();
    String params;
    Cursor cursor;

    public WordDBRecord999(Context c) {
        context = c;
    }

    public WordDBRecord999 open() throws SQLException {
        dbHelper = new WordDBHelper999(context, "WordDB", null, 10);
        database = dbHelper.getWritableDatabase(); // 1. getWritableDatabase()에서 onCreate메소드가 호출됨, 위에서 version이 1이 아닌 2,3,4 일때 onupgrade가 호출 되는 듯?
        // 주의할점 ListView에 분식집메뉴 같이 띄워쓰기 안한 후 DB에 넣을땐 분식집 메뉴 쓰면 NOT IN 써도 제외가 안되는 거!!
        return this;
    }

    public int getRowCount(String tableName) {
        Cursor cursor3 = database.rawQuery("SELECT WORD FROM " + tableName, null);
        int count = cursor3.getCount();
        cursor3.close();
        Log.v("태그","DB의 record개수는 "+count);
        return count;
    }

    public void insertRows() {
        dbInsert("KeyWordDB", "신체기관", "심장");
        dbInsert("KeyWordDB", "신체기관", "뇌");
        dbInsert("KeyWordDB", "신체기관", "간");
        dbInsert("KeyWordDB", "신체기관", "폐");
        dbInsert("KeyWordDB", "신체기관", "항문");
        dbInsert("KeyWordDB", "신체기관", "위");
        dbInsert("KeyWordDB", "신체기관", "입");
        dbInsert("KeyWordDB", "신체기관", "창자");
        dbInsert("KeyWordDB", "신체기관", "대장");
        dbInsert("KeyWordDB", "신체기관", "소장");
        dbInsert("KeyWordDB", "스포츠", "축구");
        dbInsert("KeyWordDB", "스포츠", "농구");
        dbInsert("KeyWordDB", "스포츠", "배구");
        dbInsert("KeyWordDB", "스포츠", "핸드볼");
        dbInsert("KeyWordDB", "스포츠", "야구");
        dbInsert("KeyWordDB", "스포츠", "하키");
        dbInsert("KeyWordDB", "스포츠", "럭비");
        dbInsert("KeyWordDB", "스포츠", "테니스");
        dbInsert("KeyWordDB", "스포츠", "족구");
        dbInsert("KeyWordDB", "스포츠", "당구");
        dbInsert("KeyWordDB", "패스트푸드", "피자");
        dbInsert("KeyWordDB", "패스트푸드", "햄버거");
        dbInsert("KeyWordDB", "패스트푸드", "콜라");
        dbInsert("KeyWordDB", "패스트푸드", "치킨");
        dbInsert("KeyWordDB", "패스트푸드", "감자칩");
        dbInsert("KeyWordDB", "패스트푸드", "타코");
        dbInsert("KeyWordDB", "패스트푸드", "핫도그");
        dbInsert("KeyWordDB", "패스트푸드", "샌드위치");
        dbInsert("KeyWordDB", "패스트푸드", "도넛");
        dbInsert("KeyWordDB", "패스트푸드", "부리또");
        dbInsert("KeyWordDB", "색", "빨강");
        dbInsert("KeyWordDB", "색", "주황");
        dbInsert("KeyWordDB", "색", "노랑");
        dbInsert("KeyWordDB", "색", "초록");
        dbInsert("KeyWordDB", "색", "파랑");
        dbInsert("KeyWordDB", "색", "보라");
        dbInsert("KeyWordDB", "색", "연두");
        dbInsert("KeyWordDB", "색", "하늘");
        dbInsert("KeyWordDB", "색", "베이지");
        dbInsert("KeyWordDB", "색", "검정");
        dbInsert("KeyWordDB", "교통수단", "자전거");
        dbInsert("KeyWordDB", "교통수단", "도보");
        dbInsert("KeyWordDB", "교통수단", "승용차");
        dbInsert("KeyWordDB", "교통수단", "버스");
        dbInsert("KeyWordDB", "교통수단", "기차");
        dbInsert("KeyWordDB", "교통수단", "비행기");
        dbInsert("KeyWordDB", "교통수단", "배");
        dbInsert("KeyWordDB", "교통수단", "헬리콥터");
        dbInsert("KeyWordDB", "교통수단", "지하철");
        dbInsert("KeyWordDB", "교통수단", "킥보드");
        dbInsert("KeyWordDB", "악기", "기타");
        dbInsert("KeyWordDB", "악기", "피아노");
        dbInsert("KeyWordDB", "악기", "첼로");
        dbInsert("KeyWordDB", "악기", "바이올린");
        dbInsert("KeyWordDB", "악기", "베이스 기타");
        dbInsert("KeyWordDB", "악기", "드럼");
        dbInsert("KeyWordDB", "악기", "리코더");
        dbInsert("KeyWordDB", "악기", "장구");
        dbInsert("KeyWordDB", "악기", "북");
        dbInsert("KeyWordDB", "악기", "꽹과리");
        dbInsert("KeyWordDB", "악기", "단소");
        dbInsert("KeyWordDB", "악기", "거문고");
        dbInsert("KeyWordDB", "전자제품", "컴퓨터");
        dbInsert("KeyWordDB", "전자제품", "핸드폰");
        dbInsert("KeyWordDB", "전자제품", "믹서기");
        dbInsert("KeyWordDB", "전자제품", "냉장고");
        dbInsert("KeyWordDB", "전자제품", "전자렌지");
        dbInsert("KeyWordDB", "전자제품", "가습기");
        dbInsert("KeyWordDB", "전자제품", "건조기");
        dbInsert("KeyWordDB", "전자제품", "선풍기");
        dbInsert("KeyWordDB", "전자제품", "에어콘");
        dbInsert("KeyWordDB", "전자제품", "공기청정기");
        dbInsert("KeyWordDB", "동음이의어", "배");
        dbInsert("KeyWordDB", "동음이의어", "이");
        dbInsert("KeyWordDB", "동음이의어", "등");
        dbInsert("KeyWordDB", "동음이의어", "김");
        dbInsert("KeyWordDB", "동음이의어", "눈");
        dbInsert("KeyWordDB", "동음이의어", "밤");
        dbInsert("KeyWordDB", "동음이의어", "이상");
        dbInsert("KeyWordDB", "동음이의어", "말");
        dbInsert("KeyWordDB", "동음이의어", "벌");
        dbInsert("KeyWordDB", "동음이의어", "굴");
        dbInsert("KeyWordDB", "동음이의어", "매");
        dbInsert("KeyWordDB", "동음이의어", "금");
        dbInsert("KeyWordDB", "동음이의어", "바람");
        dbInsert("KeyWordDB", "동음이의어", "사과");
        dbInsert("KeyWordDB", "동음이의어", "은행");
        dbInsert("KeyWordDB", "동음이의어", "종");
        dbInsert("KeyWordDB", "애완동물", "고슴도치");
        dbInsert("KeyWordDB", "애완동물", "개");
        dbInsert("KeyWordDB", "애완동물", "고양이");
        dbInsert("KeyWordDB", "애완동물", "달팽이");
        dbInsert("KeyWordDB", "애완동물", "기니피그");
        dbInsert("KeyWordDB", "애완동물", "앵무새");
        dbInsert("KeyWordDB", "애완동물", "뱀");
        dbInsert("KeyWordDB", "애완동물", "도마뱀");
        dbInsert("KeyWordDB", "애완동물", "물고기");
        dbInsert("KeyWordDB", "애완동물", "돼지");
        dbInsert("KeyWordDB", "애완동물", "햄스터");
        dbInsert("KeyWordDB", "애완동물", "토끼");
        dbInsert("KeyWordDB", "애완동물", "거북이");
        dbInsert("KeyWordDB", "국가", "미국");
        dbInsert("KeyWordDB", "국가", "브라질");
        dbInsert("KeyWordDB", "국가", "일본");
        dbInsert("KeyWordDB", "국가", "중국");
        dbInsert("KeyWordDB", "국가", "대한민국");
        dbInsert("KeyWordDB", "국가", "프랑스");
        dbInsert("KeyWordDB", "국가", "독일");
        dbInsert("KeyWordDB", "국가", "영국");
        dbInsert("KeyWordDB", "국가", "이탈리아");
        dbInsert("KeyWordDB", "국가", "아르헨티나");
        dbInsert("KeyWordDB", "국가", "호주");
        dbInsert("KeyWordDB", "국가", "캐나다");
        dbInsert("KeyWordDB", "국가", "멕시코");
        dbInsert("KeyWordDB", "국가", "인도");
        dbInsert("KeyWordDB", "국가", "스페인");
        dbInsert("KeyWordDB", "국가", "덴마크");
        dbInsert("KeyWordDB", "국가", "스웨덴");
        dbInsert("KeyWordDB", "국가", "스위스");
        dbInsert("KeyWordDB", "국가", "핀란드");
        dbInsert("KeyWordDB", "국가", "터키");
        dbInsert("KeyWordDB", "국가", "러시아");
        dbInsert("KeyWordDB", "도시이름", "서울");
        dbInsert("KeyWordDB", "도시이름", "홍콩");
        dbInsert("KeyWordDB", "도시이름", "도쿄");
        dbInsert("KeyWordDB", "도시이름", "대전");
        dbInsert("KeyWordDB", "도시이름", "아테네");
        dbInsert("KeyWordDB", "도시이름", "파리");
        dbInsert("KeyWordDB", "도시이름", "LA");
        dbInsert("KeyWordDB", "도시이름", "런던");
        dbInsert("KeyWordDB", "도시이름", "워싱턴");
        dbInsert("KeyWordDB", "도시이름", "밴쿠버");
        dbInsert("KeyWordDB", "도시이름", "샌프란시스코");
        dbInsert("KeyWordDB", "도시이름", "시드니");
        dbInsert("KeyWordDB", "도시이름", "베니스");
        dbInsert("KeyWordDB", "도시이름", "부산");
        dbInsert("KeyWordDB", "도시이름", "부산");
        dbInsert("KeyWordDB", "도시이름", "부산");
        dbInsert("KeyWordDB", "도시이름", "베이징");
        dbInsert("KeyWordDB", "도시이름", "상하이");
        dbInsert("KeyWordDB", "도시이름", "두바이");
        dbInsert("KeyWordDB", "도시이름", "베를린");
        dbInsert("KeyWordDB", "도시이름", "로마");
        dbInsert("KeyWordDB", "도시이름", "뉴욕");
        dbInsert("KeyWordDB", "한국도시", "서울");
        dbInsert("KeyWordDB", "한국도시", "대전");
        dbInsert("KeyWordDB", "한국도시", "인천");
        dbInsert("KeyWordDB", "한국도시", "울산");
        dbInsert("KeyWordDB", "한국도시", "부산");
        dbInsert("KeyWordDB", "한국도시", "대구");
        dbInsert("KeyWordDB", "한국도시", "춘천");
        dbInsert("KeyWordDB", "한국도시", "광주");
        dbInsert("KeyWordDB", "한국도시", "제주");
        dbInsert("KeyWordDB", "한국도시", "목포");
        dbInsert("KeyWordDB", "한국도시", "여수");
        dbInsert("KeyWordDB", "한국도시", "전주");
        dbInsert("KeyWordDB", "한국도시", "속초");
        dbInsert("KeyWordDB", "한국도시", "군산");
        dbInsert("KeyWordDB", "한국도시", "진주");
        dbInsert("KeyWordDB", "한국도시", "창원");
        dbInsert("KeyWordDB", "한국도시", "화성");
        dbInsert("KeyWordDB", "한국도시", "수원");
        dbInsert("KeyWordDB", "한국도시", "포항");
        dbInsert("KeyWordDB", "한국도시", "경주");
        dbInsert("KeyWordDB", "한국도시", "강릉");
        dbInsert("KeyWordDB", "한국도시", "평창");
        dbInsert("KeyWordDB", "한국도시", "평양");
        dbInsert("KeyWordDB", "지하철", "강남역");
        dbInsert("KeyWordDB", "지하철", "이태원역");
        dbInsert("KeyWordDB", "지하철", "신촌역");
        dbInsert("KeyWordDB", "지하철", "고려대역");
        dbInsert("KeyWordDB", "지하철", "시청역");
        dbInsert("KeyWordDB", "지하철", "서울역");
        dbInsert("KeyWordDB", "지하철", "용산역");
        dbInsert("KeyWordDB", "지하철", "분당역");
        dbInsert("KeyWordDB", "지하철", "왕십리역");
        dbInsert("KeyWordDB", "지하철", "혜화역");
        dbInsert("KeyWordDB", "지하철", "종로역");
        dbInsert("KeyWordDB", "지하철", "광화문역");
        dbInsert("KeyWordDB", "지하철", "김포공항역");
        dbInsert("KeyWordDB", "지하철", "이대역");
        dbInsert("KeyWordDB", "지하철", "홍대역");
        dbInsert("KeyWordDB", "지하철", "합정역");
        dbInsert("KeyWordDB", "지하철", "여의도역");
        dbInsert("KeyWordDB", "지하철", "신림역");
        dbInsert("KeyWordDB", "지하철", "영등포역");
        dbInsert("KeyWordDB", "지하철", "잠실역");
        dbInsert("KeyWordDB", "지하철", "건대입구역");
        dbInsert("KeyWordDB", "지하철", "명동역");
        dbInsert("KeyWordDB", "지하철", "동묘앞역");
        dbInsert("KeyWordDB", "지하철", "뚝섬유원지역");
        dbInsert("KeyWordDB", "지하철", "압구정역");
        dbInsert("KeyWordDB", "지하철", "청량리역");
        dbInsert("KeyWordDB", "유명인물", "저스틴비버");
        dbInsert("KeyWordDB", "유명인물", "비욘세");
        dbInsert("KeyWordDB", "유명인물", "오바마");
        dbInsert("KeyWordDB", "유명인물", "트럼프");
        dbInsert("KeyWordDB", "유명인물", "간디");
        dbInsert("KeyWordDB", "유명인물", "김정은");
        dbInsert("KeyWordDB", "유명인물", "타이거우즈");
        dbInsert("KeyWordDB", "유명인물", "마이클잭슨");
        dbInsert("KeyWordDB", "유명인물", "빌게이츠");
        dbInsert("KeyWordDB", "유명인물", "워렌버핏");
        dbInsert("KeyWordDB", "유명인물", "톰크루즈");
        dbInsert("KeyWordDB", "유명인물", "드웨인존슨");
        dbInsert("KeyWordDB", "유명인물", "엠마왓슨");
        dbInsert("KeyWordDB", "유명인물", "푸틴");
        dbInsert("KeyWordDB", "유명인물", "만수르");
        dbInsert("KeyWordDB", "유명인물", "아인슈타인");
        dbInsert("KeyWordDB", "유명인물", "김연아");
        dbInsert("KeyWordDB", "유명인물", "히틀러");
        dbInsert("KeyWordDB", "의류", "팬티");
        dbInsert("KeyWordDB", "의류", "양말");
        dbInsert("KeyWordDB", "의류", "바지");
        dbInsert("KeyWordDB", "의류", "티셔츠");
        dbInsert("KeyWordDB", "의류", "목도리");
        dbInsert("KeyWordDB", "의류", "모자");
        dbInsert("KeyWordDB", "의류", "장갑");
        dbInsert("KeyWordDB", "의류", "조끼");
        dbInsert("KeyWordDB", "의류", "코트");
        dbInsert("KeyWordDB", "의류", "패딩");
        dbInsert("KeyWordDB", "음료", "콜라");
        dbInsert("KeyWordDB", "음료", "사이다");
        dbInsert("KeyWordDB", "음료", "포카리스웨트");
        dbInsert("KeyWordDB", "음료", "파워에이드");
        dbInsert("KeyWordDB", "음료", "게토레이");
        dbInsert("KeyWordDB", "음료", "마운틴듀");
        dbInsert("KeyWordDB", "음료", "환타");
        dbInsert("KeyWordDB", "음료", "레몬에이드");
        dbInsert("KeyWordDB", "음료", "초록매실");
        dbInsert("KeyWordDB", "음료", "비락식혜");
        dbInsert("KeyWordDB", "한국영화", "명량");
        dbInsert("KeyWordDB", "한국영화", "국제시장");
        dbInsert("KeyWordDB", "한국영화", "신과함께");
        dbInsert("KeyWordDB", "한국영화", "극한직업");
        dbInsert("KeyWordDB", "한국영화", "기생충");
        dbInsert("KeyWordDB", "한국영화", "베테랑");
        dbInsert("KeyWordDB", "한국영화", "7번방의 선물");
        dbInsert("KeyWordDB", "한국영화", "해운대");
        dbInsert("KeyWordDB", "한국영화", "설국열차");
        dbInsert("KeyWordDB", "한국영화", "국가대표");
        dbInsert("KeyWordDB", "한국영화", "변호인");
        dbInsert("KeyWordDB", "한국영화", "부산행");
        dbInsert("KeyWordDB", "한국영화", "어벤져스");
        dbInsert("KeyWordDB", "외국영화", "어벤져스");
        dbInsert("KeyWordDB", "외국영화", "아바타");
        dbInsert("KeyWordDB", "외국영화", "타이타닉");
        dbInsert("KeyWordDB", "외국영화", "스타워즈");
        dbInsert("KeyWordDB", "외국영화", "트랜스포머");
        dbInsert("KeyWordDB", "외국영화", "배트맨");
        dbInsert("KeyWordDB", "외국영화", "슈퍼맨");
        dbInsert("KeyWordDB", "외국영화", "쥬라기 공원");
        dbInsert("KeyWordDB", "외국영화", "겨울왕국");
        dbInsert("KeyWordDB", "외국영화", "해리포터");
        dbInsert("KeyWordDB", "외국영화", "아이언맨");
        dbInsert("KeyWordDB", "외국영화", "반지의 제왕");
        dbInsert("KeyWordDB", "외국영화", "토이스토리");
        dbInsert("KeyWordDB", "외국영화", "라이온킹");
        dbInsert("KeyWordDB", "외국영화", "알라딘");
        dbInsert("KeyWordDB", "외국영화", "터미네이터");
        dbInsert("KeyWordDB", "외국영화", "미녀와 야수");
        dbInsert("KeyWordDB", "외국영화", "쿵푸팬더");
        dbInsert("KeyWordDB", "외국영화", "슈렉");
        dbInsert("KeyWordDB", "분식집메뉴", "떡볶이");
        dbInsert("KeyWordDB", "분식집메뉴", "순대");
        dbInsert("KeyWordDB", "분식집메뉴", "김밥");
        dbInsert("KeyWordDB", "분식집메뉴", "라면");
        dbInsert("KeyWordDB", "분식집메뉴", "만두");
        dbInsert("KeyWordDB", "분식집메뉴", "우동");
        dbInsert("KeyWordDB", "분식집메뉴", "떡꼬치");
        dbInsert("KeyWordDB", "분식집메뉴", "닭꼬치");
        dbInsert("KeyWordDB", "분식집메뉴", "어묵");
        dbInsert("KeyWordDB", "애니메이션", "짱구");
        dbInsert("KeyWordDB", "애니메이션", "도라에몽");
        dbInsert("KeyWordDB", "애니메이션", "안녕자두야");
        dbInsert("KeyWordDB", "애니메이션", "뽀로로");
        dbInsert("KeyWordDB", "애니메이션", "아기공룡 둘리");
        dbInsert("KeyWordDB", "애니메이션", "원피스");
        dbInsert("KeyWordDB", "애니메이션", "나루토");
        dbInsert("KeyWordDB", "애니메이션", "아따맘마");
        dbInsert("KeyWordDB", "애니메이션", "블리치");
        dbInsert("KeyWordDB", "애니메이션", "세일러문");
        dbInsert("KeyWordDB", "애니메이션", "드래곤볼");
        dbInsert("KeyWordDB", "애니메이션", "명탐정코난");
        dbInsert("KeyWordDB", "애니메이션", "톰과제리");
        dbInsert("KeyWordDB", "애니메이션", "패트와매트");
        dbInsert("KeyWordDB", "애니메이션", "핑구");
        dbInsert("KeyWordDB", "애니메이션", "빼꼼");
        dbInsert("KeyWordDB", "애니메이션", "라바");
        dbInsert("KeyWordDB", "애니메이션", "하이큐");
        dbInsert("KeyWordDB", "애니메이션", "슬램덩크");
        dbInsert("KeyWordDB", "패션브랜드", "구찌");
        dbInsert("KeyWordDB", "패션브랜드", "에르메스");
        dbInsert("KeyWordDB", "패션브랜드", "루이비똥");
        dbInsert("KeyWordDB", "패션브랜드", "프라다");
        dbInsert("KeyWordDB", "패션브랜드", "샤넬");
        dbInsert("KeyWordDB", "패션브랜드", "불가리");
        dbInsert("KeyWordDB", "패션브랜드", "자라");
        dbInsert("KeyWordDB", "패션브랜드", "아디다스");
        dbInsert("KeyWordDB", "패션브랜드", "나이키");
        dbInsert("KeyWordDB", "패션브랜드", "퓨마");
        dbInsert("KeyWordDB", "패션브랜드", "코치");
        dbInsert("KeyWordDB", "패션브랜드", "롤렉스");
        dbInsert("KeyWordDB", "패션브랜드", "스파오");
        dbInsert("KeyWordDB", "패션브랜드", "FILA");
        dbInsert("KeyWordDB", "패션브랜드", "Dior");
        dbInsert("KeyWordDB", "패션브랜드", "언더아머");
        dbInsert("KeyWordDB", "패션브랜드", "노스페이스");
        dbInsert("KeyWordDB", "차", "볼보");
        dbInsert("KeyWordDB", "차", "현대");
        dbInsert("KeyWordDB", "차", "아우디");
        dbInsert("KeyWordDB", "차", "벤츠");
        dbInsert("KeyWordDB", "차", "BMW");
        dbInsert("KeyWordDB", "차", "기아");
        dbInsert("KeyWordDB", "차", "폭스바겐");
        dbInsert("KeyWordDB", "차", "페라리");
        dbInsert("KeyWordDB", "차", "람보르기니");
        dbInsert("KeyWordDB", "차", "도요타");
        dbInsert("KeyWordDB", "차", "혼다");
        dbInsert("KeyWordDB", "차", "쉐보레");
        dbInsert("KeyWordDB", "차", "포드");
        dbInsert("KeyWordDB", "차", "포르쉐");
        dbInsert("KeyWordDB", "차", "렉서스");
        dbInsert("KeyWordDB", "취미생활", "십자수");
        dbInsert("KeyWordDB", "취미생활", "축구");
        dbInsert("KeyWordDB", "취미생활", "볼링");
        dbInsert("KeyWordDB", "취미생활", "뜨게질");
        dbInsert("KeyWordDB", "취미생활", "야구");
        dbInsert("KeyWordDB", "취미생활", "농구");
        dbInsert("KeyWordDB", "취미생활", "바둑");
        dbInsert("KeyWordDB", "취미생활", "장기");
        dbInsert("KeyWordDB", "취미생활", "체스");
        dbInsert("KeyWordDB", "취미생활", "드로잉");
        dbInsert("KeyWordDB", "취미생활", "캘리그라피");
        dbInsert("KeyWordDB", "취미생활", "종이접기");
        dbInsert("KeyWordDB", "취미생활", "공기놀이");
        dbInsert("KeyWordDB", "취미생활", "원카드");
        dbInsert("KeyWordDB", "취미생활", "훌라");
        dbInsert("KeyWordDB", "취미생활", "포커");
        dbInsert("KeyWordDB", "취미생활", "화투");
        dbInsert("KeyWordDB", "취미생활", "브루마블");
        dbInsert("KeyWordDB", "취미생활", "모노폴리");
        dbInsert("KeyWordDB", "취미생활", "젠가");
        dbInsert("KeyWordDB", "취미생활", "루미큐브");
        dbInsert("KeyWordDB", "취미생활", "우노");
        dbInsert("KeyWordDB", "취미생활", "클루");
        dbInsert("KeyWordDB", "취미생활", "마작");
        dbInsert("KeyWordDB", "취미생활", "윷놀이");
        dbInsert("KeyWordDB", "취미생활", "블랙잭");
        dbInsert("KeyWordDB", "취미생활", "오목");
        dbInsert("KeyWordDB", "취미생활", "체스");
        dbInsert("KeyWordDB", "취미생활", "장기");
        dbInsert("KeyWordDB", "카페메뉴", "아메리카노");
        dbInsert("KeyWordDB", "카페메뉴", "카페라떼");
        dbInsert("KeyWordDB", "카페메뉴", "홍차");
        dbInsert("KeyWordDB", "카페메뉴", "캐모마일");
        dbInsert("KeyWordDB", "카페메뉴", "스무디");
        dbInsert("KeyWordDB", "카페메뉴", "얼그레이");
        dbInsert("KeyWordDB", "카페메뉴", "유자차");
        dbInsert("KeyWordDB", "카페메뉴", "에스프레소");
        dbInsert("KeyWordDB", "카페메뉴", "버블티");
        dbInsert("KeyWordDB", "카페메뉴", "레모네이드");
        dbInsert("KeyWordDB", "카페메뉴", "케익");
        dbInsert("KeyWordDB", "카페메뉴", "마카롱");
        dbInsert("KeyWordDB", "카페메뉴", "롤케익");
        dbInsert("KeyWordDB", "카페메뉴", "샐러드");
        dbInsert("KeyWordDB", "카페메뉴", "샌드위치");
        dbInsert("KeyWordDB", "카페메뉴", "밀크티");
        dbInsert("KeyWordDB", "카페메뉴", "빙수");
        dbInsert("KeyWordDB", "카페메뉴", "요거트");
        dbInsert("KeyWordDB", "카페메뉴", "핫초코");
        dbInsert("KeyWordDB", "카페메뉴", "생과일주스");
        dbInsert("KeyWordDB", "학과", "수학과");
        dbInsert("KeyWordDB", "학과", "컴퓨터공학과");
        dbInsert("KeyWordDB", "학과", "정치외교학과");
        dbInsert("KeyWordDB", "학과", "역사학과");
        dbInsert("KeyWordDB", "학과", "심리학과");
        dbInsert("KeyWordDB", "학과", "언어학과");
        dbInsert("KeyWordDB", "학과", "사회학과");
        dbInsert("KeyWordDB", "학과", "경영학과");
        dbInsert("KeyWordDB", "학과", "경제과");
        dbInsert("KeyWordDB", "학과", "통계과");
        dbInsert("KeyWordDB", "학과", "화학과");
        dbInsert("KeyWordDB", "학과", "의학과");
        dbInsert("KeyWordDB", "학과", "약학과");
        dbInsert("KeyWordDB", "학과", "생물학과");
        dbInsert("KeyWordDB", "학과", "간호학과");
        dbInsert("KeyWordDB", "학과", "물리학과");
        dbInsert("KeyWordDB", "학과", "지구과학학과");
        dbInsert("KeyWordDB", "학과", "전기전자학과");
        dbInsert("KeyWordDB", "학과", "어문학과");
        dbInsert("KeyWordDB", "학과", "교육학과");
        dbInsert("KeyWordDB", "학과", "체육학과");
        dbInsert("KeyWordDB", "학과", "철학과");
        dbInsert("KeyWordDB", "학과", "미디어학과");
        dbInsert("KeyWordDB", "학과", "디자인학과");
        dbInsert("KeyWordDB", "아이돌그룹", "BTS");
        dbInsert("KeyWordDB", "아이돌그룹", "EXO");
        dbInsert("KeyWordDB", "아이돌그룹", "소녀시대");
        dbInsert("KeyWordDB", "아이돌그룹", "트와이스");
        dbInsert("KeyWordDB", "아이돌그룹", "레드벨벳");
        dbInsert("KeyWordDB", "아이돌그룹", "샤이니");
        dbInsert("KeyWordDB", "아이돌그룹", "슈퍼주니어");
        dbInsert("KeyWordDB", "아이돌그룹", "빅뱅");
        dbInsert("KeyWordDB", "아이돌그룹", "블랙핑크");
        dbInsert("KeyWordDB", "아이돌그룹", "에이핑크");
        dbInsert("KeyWordDB", "아이돌그룹", "워너원");
        dbInsert("KeyWordDB", "아이돌그룹", "투피엠");
        dbInsert("KeyWordDB", "아이돌그룹", "하이라이트");
        dbInsert("KeyWordDB", "아이돌그룹", "위너");
        dbInsert("KeyWordDB", "아이돌그룹", "아이콘");
        dbInsert("KeyWordDB", "아이돌그룹", "걸스데이");
        dbInsert("KeyWordDB", "아이돌그룹", "마마무");
        dbInsert("KeyWordDB", "아이돌그룹", "몬스터엑스");
        dbInsert("KeyWordDB", "아이돌그룹", "에프엑스");
        dbInsert("KeyWordDB", "아이돌그룹", "아스트로");
        dbInsert("KeyWordDB", "아이돌그룹", "카라");
        dbInsert("KeyWordDB", "아이돌그룹", "aoa");
        dbInsert("KeyWordDB", "아이돌그룹", "브라운아이드걸즈");
        dbInsert("KeyWordDB", "아이돌그룹", "티아라");
        dbInsert("KeyWordDB", "아이돌그룹", "itzy");
        dbInsert("KeyWordDB", "아이돌그룹", "2NE1");
        dbInsert("KeyWordDB", "아이돌그룹", "EXID");
        dbInsert("KeyWordDB", "아이돌그룹", "IOI");
        dbInsert("KeyWordDB", "아이돌그룹", "GOD");
        dbInsert("KeyWordDB", "아이돌그룹", "원더걸스");
        dbInsert("KeyWordDB", "아이돌그룹", "포미닛");
        dbInsert("KeyWordDB", "아이돌그룹", "시크릿");
        dbInsert("KeyWordDB", "아이돌그룹", "시스타");
        dbInsert("KeyWordDB", "아이돌그룹", "미스에이");
        dbInsert("KeyWordDB", "아이돌그룹", "여자친구");
        dbInsert("KeyWordDB", "축구선수", "메시");
        dbInsert("KeyWordDB", "축구선수", "호날두");
        dbInsert("KeyWordDB", "축구선수", "네이마르");
        dbInsert("KeyWordDB", "축구선수", "그리즈만");
        dbInsert("KeyWordDB", "축구선수", "수아레즈");
        dbInsert("KeyWordDB", "축구선수", "아자르");
        dbInsert("KeyWordDB", "축구선수", "레반도프스키");
        dbInsert("KeyWordDB", "축구선수", "로벤");
        dbInsert("KeyWordDB", "축구선수", "리베리");
        dbInsert("KeyWordDB", "축구선수", "사비");
        dbInsert("KeyWordDB", "축구선수", "이니에스타");
        dbInsert("KeyWordDB", "축구선수", "호나우지뉴");
        dbInsert("KeyWordDB", "축구선수", "펠레");
        dbInsert("KeyWordDB", "축구선수", "마라도나");
        dbInsert("KeyWordDB", "축구선수", "크루이프");
        dbInsert("KeyWordDB", "축구선수", "말디니");
        dbInsert("KeyWordDB", "축구선수", "베켄바워");
        dbInsert("KeyWordDB", "축구선수", "야신");
        dbInsert("KeyWordDB", "축구선수", "노이어");
        dbInsert("KeyWordDB", "축구선수", "부폰");
        dbInsert("KeyWordDB", "축구선수", "카시야스");
        dbInsert("KeyWordDB", "축구선수", "체흐");
        dbInsert("KeyWordDB", "축구선수", "드록바");
        dbInsert("KeyWordDB", "축구선수", "지단");
        dbInsert("KeyWordDB", "축구선수", "박지성");
        dbInsert("KeyWordDB", "축구선수", "손흥민");
        dbInsert("KeyWordDB", "축구선수", "이강인");
        dbInsert("KeyWordDB", "축구선수", "기성용");
        dbInsert("KeyWordDB", "축구선수", "이영표");
        dbInsert("KeyWordDB", "축구선수", "안정환");
        dbInsert("KeyWordDB", "축구선수", "차범근");
        dbInsert("KeyWordDB", "축구선수", "차두리");
        dbInsert("KeyWordDB", "NBA선수", "르브론");
        dbInsert("KeyWordDB", "NBA선수", "커리");
        dbInsert("KeyWordDB", "NBA선수", "하든");
        dbInsert("KeyWordDB", "NBA선수", "엠비드");
        dbInsert("KeyWordDB", "NBA선수", "아데토쿤보");
        dbInsert("KeyWordDB", "NBA선수", "마이클 조던");
        dbInsert("KeyWordDB", "NBA선수", "샤킬 오닐");
        dbInsert("KeyWordDB", "NBA선수", "카이리 어빙");
        dbInsert("KeyWordDB", "NBA선수", "듀란트");
        dbInsert("KeyWordDB", "NBA선수", "레너드");
        dbInsert("KeyWordDB", "NBA선수", "시몬스");
        dbInsert("KeyWordDB", "NBA선수", "자이온 윌리엄스");
        dbInsert("KeyWordDB", "NBA선수", "론조 볼");
        dbInsert("KeyWordDB", "NBA선수", "클레이 탐슨");
        dbInsert("KeyWordDB", "NBA선수", "마크 가솔");
        dbInsert("KeyWordDB", "NBA선수", "서브룩");
        dbInsert("KeyWordDB", "NBA선수", "크리스폴");
        dbInsert("KeyWordDB", "NBA선수", "돈치치");
        dbInsert("KeyWordDB", "NBA선수", "메직 존슨");
        dbInsert("KeyWordDB", "NBA선수", "래리 버드");
        dbInsert("KeyWordDB", "NBA선수", "데릭 로즈");
        dbInsert("KeyWordDB", "NBA선수", "제레미 린");
        dbInsert("KeyWordDB", "MLB선수", "트라웃");
        dbInsert("KeyWordDB", "MLB선수", "커쇼");
        dbInsert("KeyWordDB", "MLB선수", "벌렌더");
        dbInsert("KeyWordDB", "MLB선수", "그레인키");
        dbInsert("KeyWordDB", "MLB선수", "슈어저");
        dbInsert("KeyWordDB", "MLB선수", "류현진");
        dbInsert("KeyWordDB", "MLB선수", "푸홀스");
        dbInsert("KeyWordDB", "MLB선수", "미겔 카브레라");
        dbInsert("KeyWordDB", "MLB선수", "추신수");
        dbInsert("KeyWordDB", "MLB선수", "박찬호");
        dbInsert("KeyWordDB", "MLB선수", "베이브 루스");
        dbInsert("KeyWordDB", "MLB선수", "A.로드");
        dbInsert("KeyWordDB", "MLB선수", "베리 본즈");
        dbInsert("KeyWordDB", "MLB선수", "데릭 지터");
        dbInsert("KeyWordDB", "MLB선수", "웨인라이트");
        dbInsert("KeyWordDB", "MLB선수", "야큐나");
        dbInsert("KeyWordDB", "MLB선수", "오타니");
        dbInsert("KeyWordDB", "MLB선수", "소토");
        dbInsert("KeyWordDB", "MLB선수", "랜던");
        dbInsert("KeyWordDB", "MLB선수", "벨린저");
        dbInsert("KeyWordDB", "MLB선수", "먼시");
        dbInsert("KeyWordDB", "MLB선수", "터너");
        dbInsert("KeyWordDB", "MLB선수", "푸이그");
        dbInsert("KeyWordDB", "MLB선수", "강정호");
        dbInsert("KeyWordDB", "영화감독", "봉준호");
        dbInsert("KeyWordDB", "영화감독", "박찬욱");
        dbInsert("KeyWordDB", "영화감독", "크리스토퍼 놀란");
        dbInsert("KeyWordDB", "영화감독", "스티븐 스필버그");
        dbInsert("KeyWordDB", "영화감독", "제임스 카메론");
        dbInsert("KeyWordDB", "영화감독", "마이클 베이");
        dbInsert("KeyWordDB", "영화감독", "피터 잭슨");
        dbInsert("KeyWordDB", "영화감독", "리들리 스콧");
        dbInsert("KeyWordDB", "영화감독", "조지 루카스");
        dbInsert("KeyWordDB", "영화감독", "마야자키 하야오");
        dbInsert("KeyWordDB", "영화감독", "히치콕");
        dbInsert("KeyWordDB", "영화감독", "홍상수");
        dbInsert("KeyWordDB", "영화감독", "찰리채플린");
        dbInsert("KeyWordDB", "영화감독", "쿠엔틴 타란티노");
        dbInsert("KeyWordDB", "게임", "롤");
        dbInsert("KeyWordDB", "게임", "오버워치");
        dbInsert("KeyWordDB", "게임", "피파");
        dbInsert("KeyWordDB", "게임", "클래쉬로열");
        dbInsert("KeyWordDB", "게임", "배틀그라운드");
        dbInsert("KeyWordDB", "게임", "메이플스토리");
        dbInsert("KeyWordDB", "게임", "서든어택");
        dbInsert("KeyWordDB", "게임", "카트라이더");
        dbInsert("KeyWordDB", "게임", "크레이지아케이드");
        dbInsert("KeyWordDB", "게임", "던젼앤파이터");
        dbInsert("KeyWordDB", "게임", "포트나이트");
        dbInsert("KeyWordDB", "게임", "스타크래프트");
        dbInsert("KeyWordDB", "게임", "워크래프트");
        dbInsert("KeyWordDB", "게임", "디아블로");
        dbInsert("KeyWordDB", "대기업", "삼성");
        dbInsert("KeyWordDB", "대기업", "애플");
        dbInsert("KeyWordDB", "대기업", "아마존");
        dbInsert("KeyWordDB", "대기업", "현대");
        dbInsert("KeyWordDB", "대기업", "구글");
        dbInsert("KeyWordDB", "대기업", "페이스북");
        dbInsert("KeyWordDB", "대기업", "알리바바");
        dbInsert("KeyWordDB", "대기업", "LG");
        dbInsert("KeyWordDB", "대기업", "마이크로소프트");
    }

    public void dbInsert(String tableName, String category, String word) {
        Log.d(TAG, "Insert Data ");
        ContentValues contentValues = new ContentValues();
        contentValues.put("CATEGORY", category);
        contentValues.put("WORD", word);
        // 리턴값: 생성된 데이터의 id
        long id = database.insert(tableName, null, contentValues);
        Log.d(TAG, "id: " + id);
    }

    public void DBSearchCategory(String tableName) {
        // ListView에서 선택된 카테고리 제외시키기
        StringBuilder sb = new StringBuilder("");
        if (s1.ListViewCategory.size() > 0 && s1.ListViewCategory.size() != 33) {
            Log.v("태그", "if ListViewCategory의 수는 " + s1.ListViewCategory.size());
            for (String param : s1.ListViewCategory) {
                sb.append(",").append("'").append(param).append("'"); // double quote에서 single quote로 바꿈
            }
            params = sb.toString().substring(1); // substring(1)은 index0자르고 1부터 시작한다는 소리
            Log.v("태그", "params의 값은 " + params);
            String sql = "SELECT CATEGORY FROM " + tableName
                    + " WHERE CATEGORY NOT IN (?) "
                    + " ORDER BY RANDOM() LIMIT 1 ";
            sql = sql.replace("?", params);
            cursor = database.rawQuery(sql, null);

        } else if (s1.ListViewCategory.size() == 33) { // 1. 체크박스를 모두 선택한 경우
            Log.v("태그", "else ListViewCategory의 수는 " + s1.ListViewCategory.size());
            String sql = "SELECT CATEGORY FROM " + tableName
                    + " ORDER BY RANDOM() LIMIT 1 ";
            cursor = database.rawQuery(sql, null);
        } else { // 2. 체크박스를 아무것도 선택하지 않은 경우
            Log.v("태그", "else ListViewCategory의 수는 " + s1.ListViewCategory.size());
            String sql = "SELECT CATEGORY FROM " + tableName
                    + " ORDER BY RANDOM() LIMIT 1 ";
            cursor = database.rawQuery(sql, null);
        }

        while (cursor.moveToNext()) {
            //            id = cursor.getString(cursor.getColumnIndex("ID"));
            //            word = cursor.getString(cursor.getColumnIndex("WORD"));
            category = cursor.getString(cursor.getColumnIndex("CATEGORY"));
            Log.v("태그", "WordDBRecord에서 선택된 category는 " + category);
            s1.keyCategory = category;
            Log.v("태그", "선택된 keyCategory는 " + s1.keyCategory);
        }
        cursor.close();
    }

    public void DBSearchCitizenWord(String tableName) {
        Cursor cursor2 = database.rawQuery("SELECT WORD FROM " + tableName
                + " WHERE CATEGORY== " + "'" + s1.keyCategory + "'"
                + " ORDER BY RANDOM() LIMIT 1 ", null);
        while (cursor2.moveToNext()) {
//            id = cursor2.getString(cursor2.getColumnIndex("ID"));
//            category = cursor2.getString(cursor2.getColumnIndex("CATEGORY"));
            word = cursor2.getString(cursor2.getColumnIndex("WORD"));
            s1.CitizenkeyWord = word;
            Log.v("태그", "선택된 시민의 keyWord는 " + s1.CitizenkeyWord);
        }
        cursor2.close();
    }

    public void DBSearchMafiaWord(String tableName) {
        Cursor cursor2 = database.rawQuery("SELECT WORD FROM " + tableName
                + " WHERE CATEGORY== " + "'" + s1.keyCategory + "'" + " AND WORD != " + "'" + s1.CitizenkeyWord + "'"
                + " ORDER BY RANDOM() LIMIT 1 ", null);
        while (cursor2.moveToNext()) {
//            id = cursor2.getString(cursor2.getColumnIndex("ID"));
//            category = cursor2.getString(cursor2.getColumnIndex("CATEGORY"));
            word = cursor2.getString(cursor2.getColumnIndex("WORD"));
            s1.MafiakeyWord = word;
            Log.v("태그", "선택된 마피아의 keyWord는 " + s1.MafiakeyWord);
        }
        cursor2.close();
    }

    public void close() {
        database.close();
        dbHelper.close();
    }
}
